# Generated by Django 3.1.1 on 2021-04-26 17:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('water', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Water',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now=True)),
                ('amount', models.PositiveIntegerField(verbose_name='양')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='water.profile', verbose_name='사용자')),
            ],
        ),
    ]
