# Generated by Django 3.2 on 2021-04-27 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('water', '0003_auto_20210426_1739'),
    ]

    operations = [
        migrations.AlterField(
            model_name='water',
            name='amount',
            field=models.PositiveIntegerField(default=0, verbose_name='양'),
        ),
    ]
